In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/heart-disease-dataset/heart.csv

In [2]:
df=pd.read_csv("/kaggle/input/heart-disease-dataset/heart.csv")
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [3]:
df.columns

Index(['age', 'sex', 'cp', 'trestbps', 'chol', 'fbs', 'restecg', 'thalach',
       'exang', 'oldpeak', 'slope', 'ca', 'thal', 'target'],
      dtype='object')

In [4]:
# from sklearn.preprocessing import LabelEncoder

# columns_to_encode = ['Sex', 'ChestPainType', 'RestingECG', 'ExerciseAngina', 'ST_Slope']

# label_encoder = LabelEncoder()

# for column in columns_to_encode:
#     if column in df.columns:
#         df[column] = label_encoder.fit_transform(df[column])

In [5]:
df

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,52,1,0,125,212,0,1,168,0,1.0,2,2,3,0
1,53,1,0,140,203,1,0,155,1,3.1,0,0,3,0
2,70,1,0,145,174,0,1,125,1,2.6,0,0,3,0
3,61,1,0,148,203,0,1,161,0,0.0,2,1,3,0
4,62,0,0,138,294,1,1,106,0,1.9,1,3,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1020,59,1,1,140,221,0,1,164,1,0.0,2,0,2,1
1021,60,1,0,125,258,0,0,141,1,2.8,1,1,3,0
1022,47,1,0,110,275,0,0,118,1,1.0,1,1,2,0
1023,50,0,0,110,254,0,0,159,0,0.0,2,0,2,1
1024,54,1,0,120,188,0,1,113,0,1.4,1,1,3,0

In [6]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.callbacks import ModelCheckpoint
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

y = df['target']
X = df.drop('target', axis=1)

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

model = Sequential()

model.add(Dense(128, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(64, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(64, input_dim=X_train.shape[1], activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(32, activation='relu'))
model.add(Dropout(0.2))

model.add(Dense(1, activation='sigmoid')) 

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

checkpoint = ModelCheckpoint('best_model.h5', monitor='val_accuracy', mode='max', save_best_only=True, verbose=1)

model.fit(X_train, y_train, epochs=2000, batch_size=64, validation_split=0.1, callbacks=[checkpoint], verbose=1)

best_model = tf.keras.models.load_model('best_model.h5')

Epoch 1/2000
 1/12 [=>............................] - ETA: 18s - loss: 4.2391 - accuracy: 0.5156
Epoch 1: val_accuracy improved from -inf to 0.51220, saving model to best_model.h5
12/12 [==============================] - 2s 33ms/step - loss: 2.9055 - accuracy: 0.4648 - val_loss: 0.6669 - val_accuracy: 0.5122
Epoch 2/2000
 1/12 [=>............................] - ETA: 0s - loss: 1.8914 - accuracy: 0.5000
Epoch 2: val_accuracy did not improve from 0.51220
12/12 [==============================] - 0s 6ms/step - loss: 1.5926 - accuracy: 0.4621 - val_loss: 0.7833 - val_accuracy: 0.4634
Epoch 3/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.9335 - accuracy: 0.5469
Epoch 3: val_accuracy improved from 0.51220 to 0.53659, saving model to best_model.h5

/opt/conda/lib/python3.10/site-packages/keras/src/engine/training.py:3000: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

12/12 [==============================] - 0s 9ms/step - loss: 0.9783 - accuracy: 0.5108 - val_loss: 0.7013 - val_accuracy: 0.5366
Epoch 4/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.8038 - accuracy: 0.4531
Epoch 4: val_accuracy did not improve from 0.53659
12/12 [==============================] - 0s 6ms/step - loss: 0.8990 - accuracy: 0.4919 - val_loss: 0.6898 - val_accuracy: 0.5366
Epoch 5/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7652 - accuracy: 0.5000
Epoch 5: val_accuracy improved from 0.53659 to 0.64634, saving model to best_model.h5
12/12 [==============================] - 0s 9ms/step - loss: 0.8427 - accuracy: 0.5000 - val_loss: 0.6774 - val_accuracy: 0.6463
Epoch 6/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6897 - accuracy: 0.5469
Epoch 6: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7862 - accuracy: 0.5068 - val_loss: 0.6794 - val_accuracy: 0.6341
Epoch 7/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.9665 - accuracy: 0.4219
Epoch 7: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7769 - accuracy: 0.5014 - val_loss: 0.6875 - val_accuracy: 0.5488
Epoch 8/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7768 - accuracy: 0.5156
Epoch 8: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7526 - accuracy: 0.5366 - val_loss: 0.6924 - val_accuracy: 0.5244
Epoch 9/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.8130 - accuracy: 0.4688
Epoch 9: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7536 - accuracy: 0.5000 - val_loss: 0.6688 - val_accuracy: 0.6463
Epoch 10/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7531 - accuracy: 0.5469
Epoch 10: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7164 - accuracy: 0.5257 - val_loss: 0.6763 - val_accuracy: 0.6463
Epoch 11/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7317 - accuracy: 0.5312
Epoch 11: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7005 - accuracy: 0.5637 - val_loss: 0.6663 - val_accuracy: 0.6463
Epoch 12/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7178 - accuracy: 0.4844
Epoch 12: val_accuracy did not improve from 0.64634
12/12 [==============================] - 0s 6ms/step - loss: 0.7357 - accuracy: 0.5163 - val_loss: 0.6575 - val_accuracy: 0.6463
Epoch 13/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7036 - accuracy: 0.5312
Epoch 13: val_accuracy improved from 0.64634 to 0.65854, saving model to best_model.h5
12/12 [==============================] - 0s 8ms/step - loss: 0.7141 - accuracy: 0.5488 - val_loss: 0.6584 - val_accuracy: 0.6585
Epoch 14/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7164 - accuracy: 0.5312
Epoch 14: val_accuracy did not improve from 0.65854
12/12 [==============================] - 0s 6ms/step - loss: 0.7134 - accuracy: 0.5542 - val_loss: 0.6601 - val_accuracy: 0.6463
Epoch 15/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7327 - accuracy: 0.5469
Epoch 15: val_accuracy improved from 0.65854 to 0.67073, saving model to best_model.h5
12/12 [==============================] - 0s 8ms/step - loss: 0.7096 - accuracy: 0.5542 - val_loss: 0.6488 - val_accuracy: 0.6707
Epoch 16/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6941 - accuracy: 0.5938
Epoch 16: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6965 - accuracy: 0.5447 - val_loss: 0.6445 - val_accuracy: 0.6585
Epoch 17/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6399 - accuracy: 0.6250
Epoch 17: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6800 - accuracy: 0.5935 - val_loss: 0.6367 - val_accuracy: 0.6707
Epoch 18/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6715 - accuracy: 0.6250
Epoch 18: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6730 - accuracy: 0.5854 - val_loss: 0.6307 - val_accuracy: 0.6585
Epoch 19/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6468 - accuracy: 0.5938
Epoch 19: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6890 - accuracy: 0.5759 - val_loss: 0.6379 - val_accuracy: 0.6707
Epoch 20/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6307 - accuracy: 0.7344
Epoch 20: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6627 - accuracy: 0.6043 - val_loss: 0.6390 - val_accuracy: 0.6707
Epoch 21/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6273 - accuracy: 0.6406
Epoch 21: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6620 - accuracy: 0.6152 - val_loss: 0.6363 - val_accuracy: 0.6707
Epoch 22/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5205 - accuracy: 0.7656
Epoch 22: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6455 - accuracy: 0.6314 - val_loss: 0.6348 - val_accuracy: 0.6463
Epoch 23/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6456 - accuracy: 0.6094
Epoch 23: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6437 - accuracy: 0.6179 - val_loss: 0.6353 - val_accuracy: 0.6463
Epoch 24/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6868 - accuracy: 0.5938
Epoch 24: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6234 - accuracy: 0.6450 - val_loss: 0.6175 - val_accuracy: 0.6585
Epoch 25/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6121 - accuracy: 0.6406
Epoch 25: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6388 - accuracy: 0.6328 - val_loss: 0.6111 - val_accuracy: 0.6585
Epoch 26/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6388 - accuracy: 0.5625
Epoch 26: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6242 - accuracy: 0.6220 - val_loss: 0.6172 - val_accuracy: 0.6585
Epoch 27/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7071 - accuracy: 0.5781
Epoch 27: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6500 - accuracy: 0.6084 - val_loss: 0.6162 - val_accuracy: 0.6585
Epoch 28/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.7102 - accuracy: 0.6719
Epoch 28: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6370 - accuracy: 0.6450 - val_loss: 0.6204 - val_accuracy: 0.6585
Epoch 29/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6301 - accuracy: 0.5781
Epoch 29: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6233 - accuracy: 0.6287 - val_loss: 0.6202 - val_accuracy: 0.6463
Epoch 30/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6830 - accuracy: 0.5625
Epoch 30: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6406 - accuracy: 0.6179 - val_loss: 0.6164 - val_accuracy: 0.6585
Epoch 31/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6734 - accuracy: 0.6250
Epoch 31: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6160 - accuracy: 0.6667 - val_loss: 0.6101 - val_accuracy: 0.6585
Epoch 32/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6420 - accuracy: 0.6406
Epoch 32: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6078 - accuracy: 0.6748 - val_loss: 0.6049 - val_accuracy: 0.6463
Epoch 33/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6099 - accuracy: 0.6875
Epoch 33: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.6252 - accuracy: 0.6531 - val_loss: 0.6081 - val_accuracy: 0.6707
Epoch 34/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5706 - accuracy: 0.6719
Epoch 34: val_accuracy did not improve from 0.67073
12/12 [==============================] - 0s 6ms/step - loss: 0.5902 - accuracy: 0.6802 - val_loss: 0.6051 - val_accuracy: 0.6463
Epoch 35/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6054 - accuracy: 0.7500
Epoch 35: val_accuracy improved from 0.67073 to 0.68293, saving model to best_model.h5
12/12 [==============================] - 0s 9ms/step - loss: 0.6083 - accuracy: 0.6680 - val_loss: 0.6038 - val_accuracy: 0.6829
Epoch 36/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6398 - accuracy: 0.6406
Epoch 36: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5725 - accuracy: 0.6897 - val_loss: 0.6043 - val_accuracy: 0.6463
Epoch 37/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6089 - accuracy: 0.6719
Epoch 37: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.6067 - accuracy: 0.6734 - val_loss: 0.6015 - val_accuracy: 0.6585
Epoch 38/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6597 - accuracy: 0.5938
Epoch 38: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.6010 - accuracy: 0.6870 - val_loss: 0.6039 - val_accuracy: 0.6829
Epoch 39/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5842 - accuracy: 0.7031
Epoch 39: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5894 - accuracy: 0.6883 - val_loss: 0.6007 - val_accuracy: 0.6585
Epoch 40/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6381 - accuracy: 0.6250
Epoch 40: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5748 - accuracy: 0.7019 - val_loss: 0.5890 - val_accuracy: 0.6463
Epoch 41/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4893 - accuracy: 0.7812
Epoch 41: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5767 - accuracy: 0.7073 - val_loss: 0.5878 - val_accuracy: 0.6585
Epoch 42/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5694 - accuracy: 0.7344
Epoch 42: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5801 - accuracy: 0.6802 - val_loss: 0.5999 - val_accuracy: 0.6463
Epoch 43/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6190 - accuracy: 0.6562
Epoch 43: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5903 - accuracy: 0.7087 - val_loss: 0.6053 - val_accuracy: 0.6829
Epoch 44/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6025 - accuracy: 0.6250
Epoch 44: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5831 - accuracy: 0.6897 - val_loss: 0.6055 - val_accuracy: 0.6707
Epoch 45/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6722 - accuracy: 0.6250
Epoch 45: val_accuracy did not improve from 0.68293
12/12 [==============================] - 0s 6ms/step - loss: 0.5703 - accuracy: 0.7087 - val_loss: 0.6009 - val_accuracy: 0.6707
Epoch 46/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5437 - accuracy: 0.6875
Epoch 46: val_accuracy improved from 0.68293 to 0.69512, saving model to best_model.h5
12/12 [==============================] - 0s 9ms/step - loss: 0.5677 - accuracy: 0.7114 - val_loss: 0.5970 - val_accuracy: 0.6951
Epoch 47/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5634 - accuracy: 0.7500
Epoch 47: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5742 - accuracy: 0.6924 - val_loss: 0.5919 - val_accuracy: 0.6707
Epoch 48/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5127 - accuracy: 0.7344
Epoch 48: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5898 - accuracy: 0.6897 - val_loss: 0.5811 - val_accuracy: 0.6585
Epoch 49/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5635 - accuracy: 0.7031
Epoch 49: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5607 - accuracy: 0.7222 - val_loss: 0.5767 - val_accuracy: 0.6585
Epoch 50/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5550 - accuracy: 0.7031
Epoch 50: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5615 - accuracy: 0.7154 - val_loss: 0.5819 - val_accuracy: 0.6951
Epoch 51/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4650 - accuracy: 0.7344
Epoch 51: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5804 - accuracy: 0.7060 - val_loss: 0.5867 - val_accuracy: 0.6829
Epoch 52/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4898 - accuracy: 0.8438
Epoch 52: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5511 - accuracy: 0.7480 - val_loss: 0.5822 - val_accuracy: 0.6707
Epoch 53/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5640 - accuracy: 0.6875
Epoch 53: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5605 - accuracy: 0.7154 - val_loss: 0.5770 - val_accuracy: 0.6707
Epoch 54/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5533 - accuracy: 0.7031
Epoch 54: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 7ms/step - loss: 0.5407 - accuracy: 0.7236 - val_loss: 0.5673 - val_accuracy: 0.6707
Epoch 55/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5489 - accuracy: 0.7188
Epoch 55: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 7ms/step - loss: 0.5698 - accuracy: 0.7114 - val_loss: 0.5738 - val_accuracy: 0.6707
Epoch 56/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5689 - accuracy: 0.7344
Epoch 56: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5651 - accuracy: 0.7317 - val_loss: 0.5742 - val_accuracy: 0.6951
Epoch 57/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5882 - accuracy: 0.7500
Epoch 57: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5417 - accuracy: 0.7561 - val_loss: 0.5721 - val_accuracy: 0.6707
Epoch 58/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4762 - accuracy: 0.7812
Epoch 58: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5385 - accuracy: 0.7493 - val_loss: 0.5626 - val_accuracy: 0.6707
Epoch 59/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4540 - accuracy: 0.8281
Epoch 59: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5257 - accuracy: 0.7493 - val_loss: 0.5653 - val_accuracy: 0.6585
Epoch 60/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5684 - accuracy: 0.7188
Epoch 60: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5183 - accuracy: 0.7656 - val_loss: 0.5618 - val_accuracy: 0.6707
Epoch 61/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4707 - accuracy: 0.7969
Epoch 61: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5328 - accuracy: 0.7331 - val_loss: 0.5568 - val_accuracy: 0.6707
Epoch 62/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.3972 - accuracy: 0.8438
Epoch 62: val_accuracy did not improve from 0.69512
12/12 [==============================] - 0s 6ms/step - loss: 0.5120 - accuracy: 0.7547 - val_loss: 0.5653 - val_accuracy: 0.6585
Epoch 63/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4511 - accuracy: 0.7500
Epoch 63: val_accuracy improved from 0.69512 to 0.70732, saving model to best_model.h5
12/12 [==============================] - 0s 8ms/step - loss: 0.5012 - accuracy: 0.7561 - val_loss: 0.5475 - val_accuracy: 0.7073
Epoch 64/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4890 - accuracy: 0.7031
Epoch 64: val_accuracy did not improve from 0.70732
12/12 [==============================] - 0s 6ms/step - loss: 0.4994 - accuracy: 0.7588 - val_loss: 0.5844 - val_accuracy: 0.6585
Epoch 65/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5871 - accuracy: 0.7344
Epoch 65: val_accuracy improved from 0.70732 to 0.71951, saving model to best_model.h5
12/12 [==============================] - 0s 8ms/step - loss: 0.5279 - accuracy: 0.7412 - val_loss: 0.5490 - val_accuracy: 0.7195
Epoch 66/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5353 - accuracy: 0.7344
Epoch 66: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 6ms/step - loss: 0.5155 - accuracy: 0.7331 - val_loss: 0.5474 - val_accuracy: 0.7073
Epoch 67/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5714 - accuracy: 0.6406
Epoch 67: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 6ms/step - loss: 0.5000 - accuracy: 0.7412 - val_loss: 0.5431 - val_accuracy: 0.6707
Epoch 68/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.3662 - accuracy: 0.8594
Epoch 68: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 6ms/step - loss: 0.5025 - accuracy: 0.7683 - val_loss: 0.5383 - val_accuracy: 0.6951
Epoch 69/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4978 - accuracy: 0.7500
Epoch 69: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 7ms/step - loss: 0.4896 - accuracy: 0.7710 - val_loss: 0.5405 - val_accuracy: 0.7195
Epoch 70/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.6192 - accuracy: 0.6875
Epoch 70: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 6ms/step - loss: 0.5241 - accuracy: 0.7507 - val_loss: 0.5413 - val_accuracy: 0.6829
Epoch 71/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5084 - accuracy: 0.7656
Epoch 71: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 6ms/step - loss: 0.4850 - accuracy: 0.7696 - val_loss: 0.5281 - val_accuracy: 0.6951
Epoch 72/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.5253 - accuracy: 0.6875
Epoch 72: val_accuracy did not improve from 0.71951
12/12 [==============================] - 0s 6ms/step - loss: 0.4888 - accuracy: 0.7439 - val_loss: 0.5390 - val_accuracy: 0.6829
Epoch 73/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4829 - accuracy: 0.7969
Epoch 73: val_accuracy improved from 0.71951 to 0.73171, saving model to best_model.h5
12/12 [==============================] - 0s 8ms/step - loss: 0.4808 - accuracy: 0.7751 - val_loss: 0.5266 - val_accuracy: 0.7317
Epoch 74/2000
 1/12 [=>............................] - ETA: 0s - loss: 0.4754 - accuracy: 0.8438

In [7]:
best_model = tf.keras.models.load_model('best_model.h5')

In [8]:
probabilities = best_model.predict(X_test)

threshold = 0.5

binary_predictions = np.where(probabilities > threshold, 1, 0)


print("Classification Report:")
print(classification_report(y_test, binary_predictions))

7/7 [==============================] - 0s 2ms/step
Classification Report:
              precision    recall  f1-score   support

           0       0.95      0.92      0.94       102
           1       0.92      0.95      0.94       103

    accuracy                           0.94       205
   macro avg       0.94      0.94      0.94       205
weighted avg       0.94      0.94      0.94       205

In [9]:
print(binary_predictions)

[[1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [0]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [0]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]
 [0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [1]
 [1]
 [1]
 [1]
 [0]
 [0]]

In [10]:
print(y_test)

527    1
359    1
447    0
31     1
621    0
      ..
832    1
796    1
644    1
404    0
842    0
Name: target, Length: 205, dtype: int64